# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: "3.1"
# Define services
services:
  # Postgres DB
  postgres-db:
    container_name: postgres-db
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  # My Backend APP
  spring-boot-jdbc:
    container_name: spring-boot-jdbc
    image: 'zatedzernat/spring-boot-jdbc:latest'
    build: .
    ports:
      - 1150:1150
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres-db